### PR TITLE
Fix italic so it stands out when not linked

### PR DESCRIPTION
**Pull request by nickstiffler**
Changed the CSS so italic is in grey. Let me know if this is enough highlighting or if it should be a different color.
texture_italic

### CODE REVIEW

**Comment by kyook** [comment]
Would it be possible to put them in  pink?

**Comment by nickstiffler** [comment]
Pink-ish?

italic_pink

**Comment by kyook** [comment]
Yes, ideal if you can get it slightly lighter, but fine as is for now if not. 
Thanks!!

**Comment by kyook** [comment]
forgot to ask, will this be viewable regardless of species and lexica?

**Comment by nickstiffler** [comment]
Yes, but unfortunately things like "et al" and "Drosophila" will also be highlighted because they are in italics too.

**Comment by kyook** [comment]
[image: Screen Shot 2019-01-11 at 4.00.01 PM.png]
That is fine, especially with the lighter pink.  This is my current view,
so I am used to it.

**Comment by nickstiffler** [comment]
Your screenshot didn't come through, but if it is a html page, I can match it exactly with the hex code.

**Comment by kyook** [comment]
I'm not sure if you can see this page:
http://textpresso-dev.cacr.caltech.edu/cgi-bin/gsa/worm/edit.pl?docid=300487

**Comment by nickstiffler** [comment]
It is actually red (rgb(160, 0, 0)), but I can use it!

**Comment by kyook** [comment]
wait

**Comment by kyook** [comment]
The highlighting is actually red, but with the html view, it is not
that intrusive, the texture view changes things a bit, I don't know if
red would be too much.  If you can easily make the highlighting a
lighter shade of pink that would be great, but not as light as the
gray, I couldn't read those words

**Pull request merged**
