### PR TITLE
fix so only words in italic get linked

### PR DESCRIPTION
**Pull request by nickstiffler**
Only link words that are in italics. Seems to be working, but it will need some testing to make sure I am catching everything. Also, I can add a option (like a checkbox) if the old behavior is desirable for lexica that isn't in italics.

### CODE REVIEW

**Comment by kyook** [comment]
How does the checkbox work?

**Comment by nickstiffler** [comment]
Default behavior would be to link everything, but clicking the checkbox would limit linking to italicized words only.

**Comment by kyook** [comment]
could reiterative linking happen that can employ non italic linking? For example could it work that 
1. link fly gene lexicon
2. check box to remove linking to non-italic fly gene
3. link worm proteins, with aren't italicized

**Comment by nickstiffler** [comment]
Is there a reason you want to remove the non-italic genes rather than not link them in the first place? It would be much easier right now to:

**Comment by kyook** [comment]
Fly and Zebrafish have genes names like "link", "per", "egg".  When they
are italicized in the text, they are true genes, when they are not, they
are just normal common words and the links will need to be removed.

Let's just try the checkbox.  It could work ok.  My only concern is that
there may be instances when I want to link fly genes and also some other
species lexica that is not normally italicized in the paper.  But for now,
let's try the checkbox

**Comment by nickstiffler** [comment]
I think it will work. You will be able to link the fly genes with only italics, and then link a different species lexica, but not limit it to italics with the checkbox.

**Comment by kyook** [comment]
wonderful!  that would be great. Thanks Nick!

**Pull request merged**
